#!/bin/sh
# moveup:  moves the selected file(s) to parent directory
# (if able)
for arg 
do
	if [ -f ../"$arg" ];then
		echo "Filename: '$arg' already exists in parent directory."
		echo "overwrite?"; read res
		if [ $res = y -o $res = Y ];then
			mv "$arg" ../"$arg"
		fi
	else
		mv "$arg" ../"$arg"
	fi
done

